# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Welcome
    url: '#about'
    weight: 10
  - name: Team
    url: '#people'
    weight: 20
  - name: Publications
    url: '#featured'
    weight: 30
  - name: Projects
    url: '#projects'
    weight: 50
  - name: Events
    url: '#posts'
    weight: 60
  - name: Resources
    url: '#posts'
    weight: 60
  - name: Vacancies
    url: '#vacancies'
    weight: 60
  - name: Contact
    url: '#contact'
    weight: 80

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 100
